version: 2
updates:
  - package-ecosystem: "gradle"
    # Look for `build.gradle.kts` file in the `root` directory
    directory: "/"
    # Check for updates every day (weekdays)
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
