/** @deprecated Use @smithy/core/config instead. */
export {
  getHomeDir,
  ENV_PROFILE,
  DEFAULT_PROFILE,
  getProfileName,
  getSSOTokenFilepath,
  getSSOTokenFromFile,
  SSOToken,
  SharedConfigInit,
  CONFIG_PREFIX_SEPARATOR,
  loadSharedConfigFiles,
  SsoSessionInit,
  loadSsoSessionData,
  SourceProfileInit,
  parseKnownFiles,
  externalDataInterceptor,
  Profile,
  ParsedIniData,
  SharedConfigFiles,
  ReadFileOptions,
  readFile,
} from "@smithy/core/config";
