/** @deprecated Use @smithy/core/protocols instead. */
export {
  Field,
  Fields,
  FieldsOptions,
  HttpHandler,
  HttpHandlerUserInput,
  HttpRequest,
  IHttpRequest,
  HttpResponse,
  isValidHostname,
  HttpHandlerExtensionConfiguration,
  HttpHandlerExtensionConfigType,
  getHttpHandlerExtensionConfiguration,
  resolveHttpHandlerRuntimeConfig,
  FieldOptions,
  FieldPosition,
  HeaderBag,
  HttpMessage,
  HttpHandlerOptions,
} from "@smithy/core/protocols";
